'use strict';

const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');

const paths = {
  projectRoot,
  shell: path.join(projectRoot, 'index.html'),
  pages: path.join(projectRoot, 'pages'),
  manifest: path.join(projectRoot, 'builder', '.build-manifest.json'),
};

const gitignoreMarkers = {
  start: '# === Generated by builder ===',
  end: '# === End generated ===',
};

try {
  build(process.argv.slice(2));
} catch (error) {
  console.error(`Build failed: ${error.message}`);
  console.error(error);
  process.exitCode = 1;
}

//#region build

function parseArguments(argumentsList) {
  return {
    clean: argumentsList[0] === 'clean',
  };
}

function build(argumentsList) {
  const options = parseArguments(argumentsList);

  if (options.clean) {
    console.log('Clean mode is not implemented yet.');
    return;
  }

  const inputs = readBuildInputs();

  console.log('Builder foundation is working.');
  console.log(`Project root: ${paths.projectRoot}`);
  console.log(`Shell characters: ${inputs.shell.length}`);
  console.log(`Routes discovered: ${inputs.routes.length}`);

  for (const route of inputs.routes) {
    const fragment = fs.readFileSync(route.sourcePath, 'utf8');
    const metadata = extractMetadata(fragment);
    const scriptPaths = extractDataList(fragment, 'data-js');
    const stylePaths = extractDataList(fragment, 'data-css');
    const processed = processFragment(fragment);

    console.log(
      `${route.outputPath} | ${metadata.title ?? '(no title)'} | scripts:${processed.scripts.length} js:${scriptPaths.length} css:${stylePaths.length}`,
    );
  }
}

}

//#region parser

function readBuildInputs() {
  if (!fs.existsSync(paths.shell)) {
    throw new Error(`Missing shell file: ${paths.shell}`);
  }

  if (!fs.existsSync(paths.pages)) {
    throw new Error(`Missing pages directory: ${paths.pages}`);
  }

  return {
    shell: fs.readFileSync(paths.shell, 'utf8'),
    routes: discoverRoutes(),
  };
}

function discoverRoutes() {
  const routes = [];
  const routeGroups = fs.readdirSync(paths.pages, {
    withFileTypes: true,
  });

  for (const routeGroup of routeGroups) {
    if (!routeGroup.isDirectory()) {
      continue;
    }

    const groupName = routeGroup.name;
    const groupDirectory = path.join(paths.pages, groupName);
    const entries = fs.readdirSync(groupDirectory, {
      withFileTypes: true,
    });

    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith('.html')) {
        continue;
      }

      const routeName = entry.name.slice(0, -'.html'.length);
      const outputPath = getOutputPath(groupName, routeName);

      routes.push({
        groupName,
        routeName,
        sourcePath: path.join(groupDirectory, entry.name),
        outputPath,
      });
    }
  }

  routes.sort((firstRoute, secondRoute) => {
    return firstRoute.outputPath.localeCompare(secondRoute.outputPath);
  });

  return routes;
}

function getOutputPath(groupName, routeName) {
  if (groupName === 'tabs') {
    return routeName;
  }

  return `${groupName}/${routeName}`;
}

function extractMetadata(fragment) {
  const attributes = getRouteDataAttributes(fragment);

  return {
    title: getAttribute(attributes, 'data-title'),
    description: getAttribute(attributes, 'data-description') ?? '',
    hideRouteTitle: hasAttribute(attributes, 'data-hide-route-title'),
  };
}

function extractDataList(fragment, attributeName) {
  const attributes = getRouteDataAttributes(fragment);
  const rawValue = getAttribute(attributes, attributeName);

  if (rawValue === null) {
    return [];
  }

  try {
    const parsed = JSON.parse(rawValue);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function processFragment(fragment) {
  const scripts = [];

  const withoutScripts = fragment.replace(
    /<script\s*(?:defer\s*)?>([\s\S]*?)<\/script>/g,
    (innerCode) => {
      const code = innerCode.trim();

      if (code) {
        scripts.push(code);
      }

      return '';
    },
  );

  const withoutRouteData = withoutScripts.replace(
    /<route-data[\s\S]*?<\/route-data>\s*/g,
    '',
  );

  return {
    content: withoutRouteData.trim(),
    scripts,
  };
}

//#endregion

//#region helpers

function getRouteDataAttributes(fragment) {
  const match = fragment.match(/<route-data\b([^>]*)>/);

  if (!match) {
    return '';
  }

  return match[1];
}

function getAttribute(attributes, name) {
  const match = attributes.match(
    new RegExp(`${name}\\s*=\\s*("([^"]*)"|'([^']*)')`),
  );

  if (!match) {
    return null;
  }

  return match[2] ?? match[3];
}

function hasAttribute(attributes, name) {
  return attributes.includes(name);
}

//#endregion